### ISSUE TITLE
yay-bin conflicts with pacman 6

### ISSUE THREAD

**Issue by Alumniminium** [justinesmithies/sxmo-alarm#4]
```
:: yay-bin and pacman are in conflict (libalpm.so). Remove pacman? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: yay-bin and pacman are in conflict (libalpm.so>12-64)
```

The script however finishes without any other issues and still creates a working sxmo setup

**Comment by justinesmithies** [comment]
Yes that's an issue caused by the recent pacman 6 update and the pre compiled yay-bin package. There is nothing I can do until the owner of yay-bin releases an upto date build. I could use just yay but it takes ages to compile or I could switch to paru-bin which works, but atm I'm hoping for a quick fix shortly.

**Comment by Alumniminium** [comment]
yay-bin got updated and now works again
